String preetiToUnicode(String text) {
  // Full Preeti to Unicode mapping
  Map<String, String> preetiToUnicodeMap = {
    'a': 'अ',
    'aa': 'आ',
    'i': 'इ',
    'ii': 'ई',
    'u': 'उ',
    'uu': 'ऊ',
    'r': 'ऋ',
    'e': 'ए',
    'ai': 'ऐ',
    'o': 'ओ',
    'au': 'औ',
    'k': 'क',
    'kh': 'ख',
    'g': 'ग',
    'gh': 'घ',
    'ng': 'ङ',
    'ch': 'च',
    'chh': 'छ',
    'j': 'ज',
    'jh': 'झ',
    'ny': 'ञ',
    't': 'ट',
    'th': 'ठ',
    'd': 'ड',
    'dh': 'ढ',
    'n': 'ण',
    'tth': 'त',
    'tthh': 'थ',
    'dd': 'द',
    'ddh': 'ध',
    'n': 'न',
    'p': 'प',
    'ph': 'फ',
    'b': 'ब',
    'bh': 'भ',
    'm': 'म',
    'y': 'य',
    'r': 'र',
    'l': 'ल',
    'w': 'व',
    'sh': 'श',
    'ss': 'ष',
    's': 'स',
    'h': 'ह',
    'l': 'ल',
    'ksh': 'क्ष',
    'tr': 'त्र',
    'gy': 'ज्ञ',
    '0': '०',
    '1': '१',
    '2': '२',
    '3': '३',
    '4': '४',
    '5': '५',
    '6': '६',
    '7': '७',
    '8': '८',
    '9': '९',
    '।': '।',
    ',': '।',
    ':': '॥',
    ';': '।',
  };

  // Replace each Preeti character with its Unicode equivalent
  String converted = text;
  preetiToUnicodeMap.forEach((preeti, unicode) {
    converted = converted.replaceAll(preeti, unicode);
  });
  return converted;
}
