String unicodeToPreeti(String text) {
  // Full Unicode to Preeti mapping
  Map<String, String> unicodeToPreetiMap = {
    'अ': 'a',
    'आ': 'aa',
    'इ': 'i',
    'ई': 'ii',
    'उ': 'u',
    'ऊ': 'uu',
    'ऋ': 'r',
    'ए': 'e',
    'ऐ': 'ai',
    'ओ': 'o',
    'औ': 'au',
    'क': 'k',
    'ख': 'kh',
    'ग': 'g',
    'घ': 'gh',
    'ङ': 'ng',
    'च': 'ch',
    'छ': 'chh',
    'ज': 'j',
    'झ': 'jh',
    'ञ': 'ny',
    'ट': 't',
    'ठ': 'th',
    'ड': 'd',
    'ढ': 'dh',
    'ण': 'n',
    'त': 'tth',
    'थ': 'tthh',
    'द': 'dd',
    'ध': 'ddh',
    'न': 'n',
    'प': 'p',
    'फ': 'ph',
    'ब': 'b',
    'भ': 'bh',
    'म': 'm',
    'य': 'y',
    'र': 'r',
    'ल': 'l',
    'व': 'w',
    'श': 'sh',
    'ष': 'ss',
    'स': 's',
    'ह': 'h',
    'क्श': 'ksh',
    'त्र': 'tr',
    'ज्ञ': 'gy',
    '०': '0',
    '१': '1',
    '२': '2',
    '३': '3',
    '४': '4',
    '५': '5',
    '६': '6',
    '७': '7',
    '८': '8',
    '९': '9',
    '।': '।',
    '॥': '॥',
  };

  // Replace each Unicode character with its Preeti equivalent
  String converted = text;
  unicodeToPreetiMap.forEach((unicode, preeti) {
    converted = converted.replaceAll(unicode, preeti);
  });
  return converted;
}
